name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python 3.9 for build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.9 python3.9-dev python3.9-venv
          
      - name: Update Python 3.9 PATH
        run: |
          echo "Adding Python 3.9 to PATH"
          echo "/usr/bin/python3.9" >> $GITHUB_PATH
          echo "/usr/bin/python3.9" >> $PATH

      - name: Verify Python Version
        run: |
          python3.9 --version
          python3 --version

      - name: Install Buildozer dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip \
            openjdk-8-jdk libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
            libsdl2-ttf-dev libncurses5-dev libffi-dev libssl-dev \
            liblzma-dev zlib1g-dev libgdbm-dev libnss3-dev \
            libreadline-dev libsqlite3-dev wget curl llvm \
            libncursesw5-dev xz-utils tk-dev libxml2-dev \
            libxmlsec1-dev libffi-dev libbz2-dev

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade buildozer cython

      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        env:
          PATH: /opt/hostedtoolcache/Python/3.9.19/x64/bin:$PATH
        run: |
          buildozer android debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk-file
          path: .buildozer/android/platform/build-arm64-v8a/dists/Corelli/build/outputs/apk/debug/Corelli-debug.apk
